POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVhOGViNmFkODEwZDdhM2ZkMGE5MjA5MiIsImlhdCI6MTUxOTMwOTMyMX0._Yx8oI9Oypiw_zMiO4qzPeTQAXSH2ie-QZkBN2h4xbk

{
  "title":"Tokenize everything",
  "author": "Mluukkai",
  "url": "www.fullstackhy.github.io",
  "likes":1000
}